blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_list:
    path:      /blog/{page}/{article}.{_format}
    defaults:  { _controller: BlogBundle:Default:list, page: 2, _format: html }
    requirements:
          _format:  html|rss
          page:     \d+


blog_show:
    path:      /blog/{slug}
    defaults:  { _controller: BlogBundle:Default:show }


app:
    resource: '@BlogBundle/Controller/'
    prefix: /en