blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

blog_forif:
    path:      /forif
    defaults:  { _controller: BlogBundle:Blog:forif }



blog_extend:
    path:      /extend
    defaults:  { _controller: BlogBundle:Blog:extend }

blog_include:
    path:      /include
    defaults:  { _controller: BlogBundle:Blog:include }




